-- bridge.lua  (MAME side of the Python <-> MAME bridge)
-- Bridge Functionality Generated by Claude
--
-- BIG PICTURE
--   MAME is the arcade emulator. It can run Lua scripts *inside* itself, and those scripts can
--   read emulated memory and press/release the emulated arcade buttons. This script is loaded with
--   MAME's `-autoboot_script` flag (test_bridge.py does this for us).
--
--   Python can't reach inside MAME directly, so this script acts as a go-between over a local TCP
--   socket. Every video frame (~60/sec of game time):
--       1. MAME -> Python : "frame_number  ram_checksum  inputs_MAME_currently_sees"
--       2. Python -> MAME : ONE BYTE, a bitmask of which buttons to hold for the next frame
--   MAME pauses at step 2 until Python answers, so the game advances exactly one frame per
--   Python decision ("lockstep"). That is what makes this usable for RL: the agent is never late.
--
-- THE SOCKET DIRECTION IS BACKWARDS FROM WHAT YOU'D EXPECT
--   MAME's Lua socket is a *server* (it listens on port 5000). Python is the *client* and connects.

local sock = emu.file("rwc")   -- MAME's generic file object; a "socket.host:port" name makes it a TCP socket
assert(sock:open("socket.127.0.0.1:5000") == nil, "can't listen on :5000")  -- open() returns nil on success

local m = manager.machine      -- handle to the running emulated machine (ports, CPUs, video, ...)
local mem = m.devices[":maincpu"].spaces["program"]  -- main CPU's memory, readable byte by byte

-- Which emulated arcade controls Python can press. The position in this list is the bit number
-- in the byte Python sends: 1st entry = bit 0 (value 1), 2nd = bit 1 (value 2), 3rd = 4, 4th = 8, 5th = 16.
-- Each entry is {I/O port name, button name}. Names come from MAME's definition of the game
-- (`mame galaga88 -listxml` shows them). If a lookup below fails, the name is wrong for that game.
local MAP = {
  {":COIN", "Coin 1"}, {":CONTROL0", "1 Player Start"},
  {":CONTROL0", "P1 Left"}, {":CONTROL0", "P1 Right"}, {":CONTROL0", "P1 Button 1"},
}
local fields = {}   -- fields[i] = the emulator's "button" object for MAP[i]
for i, e in ipairs(MAP) do fields[i] = m.ioport.ports[e[1]].fields[e[2]] end

local buf, frame = "", 0   -- buf: bytes received from Python but not used yet; frame: frame counter

-- MAME calls this function once at the end of every emulated video frame.
emu.register_frame_done(function()
  frame = frame + 1

  -- OBSERVATION (stand-in): a cheap checksum of the first 1 KB of main-CPU memory. Python only
  -- uses it to confirm the game state is changing.
  local h = 0
  for a = 0, 0x3ff do h = (h * 31 + mem:read_u8(a)) % 4294967296 end

  -- READ-BACK: ask MAME's emulated input ports which of our buttons they currently report as
  -- pressed, and pack that into the same bitmask format. If this matches what Python sent last
  -- frame, the input really reached the emulated hardware (that's the proof the bridge works).
  -- Arcade inputs are "active" at a non-default value, so we compare against the idle value (defvalue).
  local read = 0
  for i, f in ipairs(fields) do
    if f and (f.port:read() & f.mask) ~= (f.defvalue & f.mask) then read = read | (1 << (i - 1)) end
  end

  -- Step 1: report to Python, one text line per frame.
  sock:write(string.format("%d %d %d\n", frame, h, read))

  -- Step 2: block (up to 5 s) until Python's one-byte reply arrives. This wait is what keeps the
  -- two programs in lockstep. The 5 s timeout only matters at startup, before Python has connected.
  local t = os.clock()
  while #buf < 1 and os.clock() - t < 5 do buf = buf .. sock:read(1) end
  if #buf < 1 then return end   -- no reply: leave inputs as they were and carry on
  local mask = buf:byte(1); buf = buf:sub(2)

  -- ACTION: press (1) or release (0) each button according to its bit in the mask. These presses
  -- take effect on the next emulated frame, exactly as if a player were holding the physical button.
  for i, f in ipairs(fields) do if f then f:set_value((mask >> (i - 1)) & 1) end end
end)
